Algoritmo "circulo"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : JAILSON COSTA DOS SANTOS
// Descrição   : sistema para mostrar a area de um circulo
// Autor(a)    : Lucas Alexandre Santana
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis
area, raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite o raio: ")
Leia(raio)
area<- pi * raio^2
escreva(area)
Fimalgoritmo