Algoritmo "DecisaoComposta"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : codigo de descisão Composta
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2024
Var
   // Seção de Declarações das variáveis
   nunero:int

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   se numero > 10 entao
      escreval("numero maior que 10")
   senao
   escreva("numero menor que 10")

Fimalgoritmo