Algoritmo "DecisaoSimples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : codigo de descisão simples
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2024
Var
   // Seção de Declarações das variáveis
   nunero:int

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   se numero > 10 entao
   escreval("numero maior que 10")

Fimalgoritmo